[project]
name = "repl-nix-excelinvoiceeditor"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openpyxl>=3.1.5",
    "streamlit>=1.40.1",
]
